import json
import os

with open(r'd:\Users\ta5mg\Desktop\pdftools\PdfTool\strings.json', 'r', encoding='utf-8') as f:
    strings = json.load(f)

# Hardcode translations
translations = {
  "veya dosyayı buraya sürükleyin": "or drag the file here",
  "Split": "Split",
  "Filigran Ekle": "Add Watermark",
  "Sayfa Sayısı: 12": "Page Count: 12",
  "PDF belgenizi sayfa aralıklarına göre parçalayın veya tüm sayfaları ayrı ayrı dosyalara bölün.": "Split your PDF document by page ranges or split all pages into separate files.",
  "PNG (Kayıpsız / Şeffaflık)": "PNG (Lossless / Transparency)",
  "Şifrele / Çöz": "Encrypt / Decrypt",
  "Filigran Ayarları": "Watermark Settings",
  "Tahoma": "Tahoma",
  "ExtractImage": "ExtractImage",
  "Compress": "Compress",
  "Filigran Metni": "Watermark Text",
  "PDF belgesinden çıkarmak istediğiniz sayfaları seçip yeni belgenizi kaydedin.": "Select the pages you want to remove from the PDF document and save your new document.",
  "Ayıklanacak Sayfa Numaraları": "Page Numbers to Extract",
  "Times New Roman": "Times New Roman",
  "Sayfa Silme": "Delete Page",
  "Birden fazla PDF dosyasını tek dosyada birleştirin.": "Merge multiple PDF files into a single file.",
  "Delete": "Delete",
  "PDF içerisine gömülü olan görselleri topluca klasöre çıkarın.": "Extract all embedded images in the PDF into a folder.",
  "Örn: 2, 4, 6-8 (Gereksiz sayfalar)": "E.g.: 2, 4, 6-8 (Unnecessary pages)",
  "Dosya Ekle": "Add File",
  "Hepsi": "All",
  "Ölçek (%)": "Scale (%)",
  "Belgenizin her sayfasını ayrı bir resim dosyası (PNG veya JPG) olarak dışa aktarın.": "Export each page of your document as a separate image file (PNG or JPG).",
  "Sıkıştır ve Kaydet": "Compress and Save",
  "PDF dosyanızın boyutunu optimize edin.": "Optimize the size of your PDF file.",
  "Filigran Ekle ve Kaydet": "Add Watermark and Save",
  "Şifre (Açılış/Sahip)": "Password (Open/Owner)",
  "PDF Sıkıştır": "Compress PDF",
  "Sayfa Döndürme": "Rotate Page",
  "Sol Alt": "Bottom Left",
  "Calibri": "Calibri",
  "PDF'i Böl ve Kaydet": "Split and Save PDF",
  "Açık/Koyu Tema": "Light/Dark Theme",
  "Filigran Ekleme": "Add Watermark",
  "Silme Ayarları": "Delete Settings",
  "Koyu Gri": "Dark Gray",
  "Kayıt Klasörü": "Save Folder",
  "300 DPI (Yüksek Kalite/Baskı)": "300 DPI (High Quality/Print)",
  "Protect": "Protect",
  "Farklı PDF Seç": "Select Different PDF",
  "PDF Seçin": "Select PDF",
  "Yukarı Taşı": "Move Up",
  "Uygula ve Kaydet": "Apply and Save",
  "İşlem başarıyla tamamlandı.": "Operation completed successfully.",
  "Kırmızı (Varsayılan)": "Red (Default)",
  "Teal": "Teal",
  "Görselleri Çıkar": "Extract Images",
  "PDF belgesindeki tüm gömülü görselleri klasöre çıkarın.": "Extract all embedded images in the PDF document into a folder.",
  "Resim dosyalarını (PNG, JPG, BMP) seçin ve bunları tek bir PDF belgesi olarak derleyin.": "Select image files (PNG, JPG, BMP) and compile them into a single PDF document.",
  "Büyüklük (Punto)": "Size (Point)",
  "90° Saat Yönünde": "90° Clockwise",
  "KOPYA": "COPY",
  "Görsele Çevir": "Convert to Image",
  "Sıkıştırma Ayarları": "Compression Settings",
  "Silinecek Sayfa Numaraları": "Page Numbers to Delete",
  "PDF Bölme": "Split PDF",
  "Örn: 1-3, 5, 8-10": "E.g.: 1-3, 5, 8-10",
  "Seçilmedi...": "Not selected...",
  "Görsellerden PDF Oluşturma": "Create PDF from Images",
  "ExtractText": "ExtractText",
  "PDF Böl": "Split PDF",
  "Yazı Tipi": "Font",
  "Rotate": "Rotate",
  "Konum": "Position",
  "Hızlı (Düşük Sıkıştırma)": "Fast (Low Compression)",
  "Görselden PDF'e": "Image to PDF",
  "Şifrele/Çöz": "Encrypt/Decrypt",
  "PDF sayfalarının alt kısmına sayfa numarası ekleyin.": "Add page numbers to the bottom of the PDF pages.",
  "Sayfa Aralığı": "Page Range",
  "Resimlerinizi tek bir PDF belgesine dönüştürün.": "Convert your images into a single PDF document.",
  "Sol Üst": "Top Left",
  "PDF Birleştirme": "Merge PDF",
  "Örn: Hepsi, 1, 3-5, 8": "E.g.: All, 1, 3-5, 8",
  "150 DPI (Önerilen/Hızlı)": "150 DPI (Recommended/Fast)",
  "96 DPI (Düşük/Ekran)": "96 DPI (Low/Screen)",
  "Dosya türüne göre uygun araca otomatik olarak yönlendirilirsiniz.": "You will automatically be redirected to the appropriate tool based on file type.",
  "Home": "Home",
  "Sayfa Döndür": "Rotate Page",
  "Numara Ekle": "Add Number",
  "Yazı Tipi Boyutu": "Font Size",
  "Listeden Kaldır": "Remove from List",
  "Her Sayfayı Ayrı PDF Yap": "Extract Each Page as PDF",
  "Belirli Sayfaları Ayıkla": "Extract Specific Pages",
  "Sayfa Numarası Ekle": "Add Page Number",
  "Metinleri/İçeriği Sıkıştır": "Compress Text/Content",
  "Resim Filigranı": "Image Watermark",
  "PageNumber": "PageNumber",
  "Metin Çıkar": "Extract Text",
  "Görsel Formatı": "Image Format",
  "Format": "Format",
  "Metni Çıkar (.txt)": "Extract Text (.txt)",
  "Görsel Çıkarma": "Extract Image",
  "file.pdf": "file.pdf",
  "Orta (Merkez)": "Center (Middle)",
  "PDF'e Dönüştür": "Convert to PDF",
  "Seçilenleri Sil ve Kaydet": "Delete Selected and Save",
  "Sayfalara otomatik olarak sayfa numaraları ekleyin.": "Automatically add page numbers to pages.",
  "PDF veya Görsellerinizi Buraya Sürükleyip Bırakın": "Drag and Drop your PDF or Images Here",
  "MEGPdf Araç Kutusu'na Hoş Geldiniz": "Welcome to MEGPdf Toolbox",
  "PDF Birleştir": "Merge PDF",
  "PDF'in içerisindeki tüm metinleri TXT dosyası olarak dışa aktarın.": "Export all texts within the PDF as a TXT file.",
  "Mavi": "Blue",
  "Belgenize metin veya resim biçiminde filigranlar (logo/damga) uygulayın.": "Apply text or image watermarks (logo/stamp) to your document.",
  "Courier New": "Courier New",
  "Görselleri Klasöre Çıkar": "Extract Images to Folder",
  "PDF belgenizi sayfalara bölün veya ayıklayın.": "Split or extract your PDF document into pages.",
  "Sağ Üst": "Top Right",
  "270° (90° Saat Yönü Tersi)": "270° (90° Counterclockwise)",
  "Tüm görselleri çıkar": "Extract all images",
  "Sayfalara metin veya görsel filigranlar basın.": "Stamp text or image watermarks onto pages.",
  "Resim Dosyası": "Image File",
  "Ana Sayfa": "Home",
  "Bölme Ayarları": "Split Settings",
  "En İyi (Yüksek Sıkıştırma)": "Best (High Compression)",
  "Resim Olarak Dışa Aktar": "Export as Image",
  "Aşağıdaki listeye eklediğiniz PDF dosyalarını sırasıyla tek bir belgede birleştirir.": "Merges the PDF files you add to the list below sequentially into a single document.",
  "Opaklık (Şeffaflık)": "Opacity (Transparency)",
  "MEGPdf - Modern PDF Araç Kutusu": "MEGPdf - Modern PDF Toolbox",
  "Şifre Ekle": "Add Password",
  "Sayfa Numarası": "Page Number",
  "PDF Sıkıştırma": "Compress PDF",
  "Merge": "Merge",
  "PDF'i Görsele Dönüştürme": "Convert PDF to Image",
  "Metin Filigranı": "Text Watermark",
  "PDF belgesinden gereksiz sayfaları çıkarın.": "Remove unnecessary pages from the PDF document.",
  "Sıkıştırma Seviyesi": "Compression Level",
  "Mesafe (Kenar Boşluğu)": "Margin (Spacing)",
  "ToImage": "ToImage",
  "Görselleri Sıkıştır (JPEG)": "Compress Images (JPEG)",
  "Renk": "Color",
  "Metin Çıkarma": "Extract Text",
  "Belirli sayfaları veya tüm sayfaları döndürün.": "Rotate specific pages or all pages.",
  "Siyah": "Black",
  "PDF sayfalarını yüksek çözünürlüklü resim yapın.": "Turn PDF pages into high-resolution images.",
  "ToPdf": "ToPdf",
  "Seçilen sayfaları ayrı ayrı PDF olarak ayıkla": "Extract selected pages as separate PDFs",
  "Döndürme Açısı (°)": "Rotation Angle (°)",
  "Çözünürlük (DPI)": "Resolution (DPI)",
  "Görsel Ekle": "Add Image",
  "Döndürme Açısı": "Rotation Angle",
  "JPEG (Küçük Boyut)": "JPEG (Small Size)",
  "Numara Ekle ve Kaydet": "Add Number and Save",
  "Sağ Alt": "Bottom Right",
  "PDF içerisindeki tüm metni bir TXT dosyasına aktarın.": "Export all text in the PDF into a TXT file.",
  "PDF belgenize şifre koyun veya şifreyi kaldırın.": "Add or remove a password to your PDF document.",
  "PDF dosyasına parola koyun veya kaldırın.": "Set or remove a password for the PDF file.",
  "PDF'leri Birleştir": "Merge PDFs",
  "Verdana": "Verdana",
  "Listeyi Temizle": "Clear List",
  "Aşağı Taşı": "Move Down",
  "Normal": "Normal",
  "İşlem Türü": "Operation Type",
  "Sadece benzersiz görselleri çıkar": "Extract unique images only",
  "Sayfa 1 / 1": "Page 1 / 1",
  "Arial": "Arial",
  "Listeye en az 1 görsel ekleyin.": "Add at least 1 image to the list.",
  "Sayfa Sil": "Delete Page",
  "Döndür ve Kaydet": "Rotate and Save",
  "Döndürme Ayarları": "Rotation Settings",
  "Görsel Ayarları": "Image Settings",
  "Şifre Kaldır": "Remove Password",
  "Watermark": "Watermark",
  "PDF dosyalarınız üzerinde hızlı ve güvenli işlemler gerçekleştirin.": "Perform fast and secure operations on your PDF files.",
  "Belgenizin belirli sayfalarını seçerek saat yönünde döndürün.": "Select specific pages of your document and rotate them clockwise.",
  "Seç": "Select",
  "Listeye en az 2 PDF ekleyin.": "Add at least 2 PDFs to the list.",
  "MEGPdf": "MEGPdf"
}

os.makedirs(r'd:\Users\ta5mg\Desktop\pdftools\PdfTool\Languages', exist_ok=True)

tr_lines = ['<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:system="clr-namespace:System;assembly=mscorlib">']
en_lines = ['<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:system="clr-namespace:System;assembly=mscorlib">']

# We must escape XML characters in translations
def escape_xml(text):
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;').replace("'", '&apos;')

for tr, key in strings.items():
    en = translations.get(tr, tr)
    tr_lines.append(f'    <system:String x:Key="{key}">{escape_xml(tr)}</system:String>')
    en_lines.append(f'    <system:String x:Key="{key}">{escape_xml(en)}</system:String>')

tr_lines.append('</ResourceDictionary>')
en_lines.append('</ResourceDictionary>')

with open(r'd:\Users\ta5mg\Desktop\pdftools\PdfTool\Languages\tr.xaml', 'w', encoding='utf-8') as f:
    f.write('\n'.join(tr_lines))

with open(r'd:\Users\ta5mg\Desktop\pdftools\PdfTool\Languages\en.xaml', 'w', encoding='utf-8') as f:
    f.write('\n'.join(en_lines))

print("Created resource dictionaries")
